import { useEffect, useState, useRef, useCallback } from "react";
import "./App.css";
import { supabase } from "./supabaseClient";

const API = "/api/analyze";

function App() {
  // State
  const [inputText, setInputText] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [history, setHistory] = useState([]);
  const [examples, setExamples] = useState([]);
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const [toast, setToast] = useState({ show: false, message: "" });

  const loadingMessages = [
    "SCANNING PAYLOAD...",
    "ANALYZING PATTERNS...",
    "DETECTING THREATS...",
    "EVALUATING RISK LEVEL...",
    "GENERATING REPORT..."
  ];
  const [loadingMsgIndex, setLoadingMsgIndex] = useState(0);
  const loadingIntervalRef = useRef(null);

  // Load examples and history on mount
  useEffect(() => {
    loadHistory();
  }, []);

  // Loading message animation
  useEffect(() => {
    if (isLoading) {
      loadingIntervalRef.current = setInterval(() => {
        setLoadingMsgIndex(prev => (prev + 1) % loadingMessages.length);
      }, 1500);
    } else {
      if (loadingIntervalRef.current) {
        clearInterval(loadingIntervalRef.current);
      }
    }
    return () => {
      if (loadingIntervalRef.current) {
        clearInterval(loadingIntervalRef.current);
      }
    };
  }, [isLoading]);

  const loadExamples = async () => {
    try {
      const response = await fetch("/api/examples");
      if (response.ok) {
        const data = await response.json();
        setExamples(data.examples || []);
      }
    } catch (err) {
      console.error("Failed to load examples:", err);
    }
  };

 const loadHistory = async () => {
  const { data, error } = await supabase
    .from("analyses")
    .select("*")
    .order("created_at", { ascending: false });

  if (!error) {
    setHistory(data);
  }
};

  const loadExample = (type) => {
    const example = examples.find(ex => ex.type === type);
    if (example) {
      setInputText(example.content);
      setError("");
      setResult(null);
      showToast(`Loaded ${example.name} example`);
    }
  };

  const clearInput = () => {
    setInputText("");
    setError("");
    setResult(null);
  };

  const analyzeInput = async () => {
  const text = inputText.trim();

  if (text.length < 10) {
    setError("Input too short. Please provide at least 10 characters.");
    return;
  }

  setError("");
  setResult(null);
  setIsLoading(true);

  try {
    const response = await fetch(`${API}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json"
      },
      body: JSON.stringify({ text: inputText })
    });

    const data = await response.json();

    // 🔥 Parse AI response
   const parsed =
  typeof data.result === "string"
    ? JSON.parse(data.result)
    : data.result;

    const newResult = {
      ...parsed,
      timestamp: new Date().toISOString()
    };

    setResult(newResult);

    // 💾 Save to Supabase
    await supabase.from("analyses").insert([
      {
        input_text: text,
        risk: parsed.risk,
        explanation: parsed.explanation,
        fixes: parsed.fixes
      }
    ]);

    loadHistory();

  } catch (err) {
    setError("Analysis failed. Please try again.");
  } finally {
    setIsLoading(false);
  }
};

  const copyResults = async () => {
    if (!result) return;
    
    const text = `Security Analysis Report
========================
Risk Level: ${result.risk.toUpperCase()}

Analysis:
${result.explanation}

Recommended Actions:
${result.fixes.map((fix, i) => `${i + 1}. ${fix}`).join('\n')}

Analyzed at: ${new Date(result.timestamp).toLocaleString()}
Generated by SafeScan AI`;

    try {
      await navigator.clipboard.writeText(text);
      showToast("Results copied to clipboard");
    } catch (err) {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      textarea.style.position = "fixed";
      textarea.style.opacity = "0";
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      showToast("Results copied to clipboard");
    }
  };

const deleteHistoryItem = async (id) => {
  await supabase.from("analyses").delete().eq("id", id);
  setHistory(prev => prev.filter(item => item.id !== id));
};

 const clearHistory = async () => {
  if (!window.confirm("Clear all analysis history?")) return;

  await supabase.from("analyses").delete().neq("id", "0");
  setHistory([]);
  setResult(null);
};

  const showHistoryItem = (item) => {
  setResult({
    id: item.id,
    risk: item.risk,
    explanation: item.explanation,
    fixes: item.fixes,
    timestamp: item.created_at
  });
};

  const showToast = (message) => {
    setToast({ show: true, message });
    setTimeout(() => setToast({ show: false, message: "" }), 3000);
  };

  const formatTime = (timestamp) => {
    const date = new Date(timestamp);
    const now = new Date();
    const diff = now - date;
    
    if (diff < 60000) return "Just now";
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m ago`;
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h ago`;
    if (diff < 604800000) return `${Math.floor(diff / 86400000)}d ago`;
    
    return date.toLocaleDateString();
  };

  const getRiskClass = (risk) => {
    const r = risk?.toLowerCase() || "";
    if (r === "low") return "risk-low";
    if (r === "medium") return "risk-medium";
    if (r === "high") return "risk-high";
    return "";
  };

  return (
    <div className="app-container">
      {/* Sidebar */}
      <aside className={`sidebar ${sidebarOpen ? "open" : ""}`} id="sidebar">
        <div className="sidebar-header">
          <h3 className="sidebar-title">
            <i className="ph ph-clock-counter-clockwise"></i>
            ANALYSIS HISTORY
          </h3>
          <button 
            className="btn-terminal btn-secondary" 
            onClick={clearHistory}
            data-testid="clear-history-btn"
            aria-label="Clear all history"
          >
            <i className="ph ph-trash"></i>
          </button>
        </div>
        <div className="history-list" data-testid="history-list">
          {history.length === 0 ? (
            <div className="history-empty">
              <i className="ph ph-folder-open" style={{ fontSize: "2rem", marginBottom: "0.5rem" }}></i>
              <p>No analysis history yet</p>
            </div>
          ) : (
            history.map(item => (
              <div 
                key={item.id} 
                className="history-item" 
                data-testid={`history-item-${item.id}`}
                onClick={() => showHistoryItem(item)}
              >
                <div className="history-item-header">
                  <span className={`history-risk ${item.risk_level.toLowerCase()}`}>
                    {item.risk_level}
                  </span>
                  <div style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
                    <span className="history-time">{formatTime(item.timestamp)}</span>
                    <button 
                      className="history-delete" 
                      data-testid={`delete-history-${item.id}`}
                      onClick={(e) => { e.stopPropagation(); deleteHistoryItem(item.id); }}
                      aria-label="Delete this analysis"
                    >
                      <i className="ph ph-x"></i>
                    </button>
                  </div>
                </div>
                <p className="history-preview">{item.input_preview}</p>
              </div>
            ))
          )}
        </div>
      </aside>

      {/* Mobile Sidebar Toggle */}
      <button 
        className="sidebar-toggle d-lg-none" 
        onClick={() => setSidebarOpen(!sidebarOpen)}
        data-testid="sidebar-toggle"
        aria-label="Toggle history sidebar"
      >
        <i className="ph ph-list"></i>
      </button>

      {/* Main Content */}
      <main className="main-content">
        {/* Header */}
        <header className="app-header">
          <div className="logo-section">
            <div className="logo">
              <i className="ph ph-shield-check"></i>
            </div>
            <div>
              <h1 className="app-title">SAFESCAN AI</h1>
              <p className="app-subtitle">CYBERSECURITY ANALYSIS TERMINAL</p>
            </div>
          </div>
          <div className="status-indicator">
            <span className="status-dot"></span>
            <span className="status-text">SYSTEM ONLINE</span>
          </div>
        </header>

        {/* Input Section */}
        <section className="input-section">
          <div className="section-header">
            <label htmlFor="input-text" className="section-label">
              <i className="ph ph-terminal-window"></i>
              INPUT PAYLOAD
            </label>
            <div className="example-buttons">
              <button 
                className="btn-terminal btn-secondary btn-sm" 
                data-testid="example-log-btn"
                onClick={() => loadExample("log")}
              >
                LOG
              </button>
              <button 
                className="btn-terminal btn-secondary btn-sm" 
                data-testid="example-code-btn"
                onClick={() => loadExample("code")}
              >
                CODE
              </button>
              <button 
                className="btn-terminal btn-secondary btn-sm" 
                data-testid="example-email-btn"
                onClick={() => loadExample("email")}
              >
                EMAIL
              </button>
            </div>
          </div>
          <div className="input-wrapper">
            <textarea 
              id="input-text"
              data-testid="input-text"
              placeholder="Paste logs, code, or email content here for security analysis..."
              aria-label="Input text for security analysis"
              rows={8}
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
            />
            <div className="input-footer">
              <span className="char-count">{inputText.length.toLocaleString()} / 50,000</span>
              <button 
                className="btn-terminal btn-secondary btn-sm" 
                onClick={clearInput}
                data-testid="clear-input-btn"
              >
                <i className="ph ph-x"></i> CLEAR
              </button>
            </div>
          </div>
          <button 
            className="btn-terminal btn-primary analyze-btn" 
            onClick={analyzeInput}
            disabled={isLoading}
            data-testid="analyze-btn"
            aria-label="Analyze input for security issues"
          >
            <i className="ph ph-magnifying-glass"></i>
            {isLoading ? "ANALYZING..." : "ANALYZE PAYLOAD"}
          </button>
        </section>

        {/* Loading Section */}
        {isLoading && (
          <div className="loading-section">
            <div className="loading-bar">
              <div className="loading-progress"></div>
            </div>
            <div className="loading-text">
              <span className="loading-brackets">[</span>
              <span className="loading-dots">||||</span>
              <span className="loading-brackets">]</span>
              <span className="loading-message">{loadingMessages[loadingMsgIndex]}</span>
            </div>
          </div>
        )}

        {/* Error Section */}
        {error && (
          <div className="error-section" data-testid="error-section">
            <div className="error-content">
              <i className="ph ph-warning-circle"></i>
              <span className="error-message" data-testid="error-message">{error}</span>
            </div>
          </div>
        )}

        {/* Results Section */}
        {result && (
          <section className="results-section" data-testid="results-section">
            <div className="section-header">
              <label className="section-label">
                <i className="ph ph-file-text"></i>
                ANALYSIS RESULTS
              </label>
              <button 
                className="btn-terminal btn-secondary btn-sm" 
                onClick={copyResults}
                data-testid="copy-results-btn"
                aria-label="Copy results to clipboard"
              >
                <i className="ph ph-copy"></i> COPY
              </button>
            </div>
            
            {/* Risk Level */}
            <div className="risk-container">
              <span className="risk-label">THREAT LEVEL</span>
              <span className={`risk-badge ${getRiskClass(result.risk)}`} data-testid="risk-badge">
                {result.risk?.toUpperCase()}
              </span>
            </div>

            {/* Explanation */}
            <div className="explanation-panel">
              <h4 className="panel-title">
                <i className="ph ph-info"></i>
                ANALYSIS
              </h4>
              <p className="explanation-text" data-testid="explanation-text">{result.explanation}</p>
            </div>

            {/* Fixes */}
            <div className="fixes-panel">
              <h4 className="panel-title">
                <i className="ph ph-wrench"></i>
                RECOMMENDED ACTIONS
              </h4>
              <ul className="fixes-list" data-testid="fixes-list">
                {result.fixes?.map((fix, index) => (
                  <li key={index}>{fix}</li>
                ))}
              </ul>
            </div>

            {/* Timestamp */}
            <div className="result-meta">
              <span className="meta-label">ANALYZED AT:</span>
              <span className="meta-value" data-testid="result-timestamp">
                {new Date(result.timestamp).toLocaleString()}
              </span>
            </div>
          </section>
        )}
      </main>

      {/* Toast Notification */}
      <div className="toast-container">
        <div className={`toast ${toast.show ? "show" : ""}`} role="alert" aria-live="assertive" data-testid="toast">
          <i className="ph ph-check-circle toast-icon"></i>
          <span className="toast-message">{toast.message}</span>
        </div>
      </div>
    </div>
  );
}

export default App;
